import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { Mail, FileText, ListTodo, Search, MessageSquare, AlertTriangle, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — WorkAI" },
      { name: "description", content: "Your AI-powered workplace productivity dashboard." },
    ],
  }),
  component: Index,
});

const tools = [
  { title: "Smart Email Generator", desc: "Draft professional emails from a short brief.", url: "/email", icon: Mail },
  { title: "Meeting Notes Summarizer", desc: "Turn raw notes into clean summaries & action items.", url: "/meetings", icon: FileText },
  { title: "AI Task Planner", desc: "Break goals into an organized, prioritized plan.", url: "/planner", icon: ListTodo },
  { title: "AI Research Assistant", desc: "Get structured briefs on any topic, fast.", url: "/research", icon: Search },
  { title: "AI Chatbot", desc: "Conversational assistant for any workplace task.", url: "/chat", icon: MessageSquare },
];

function Index() {
  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-8 md:px-8 md:py-12">
      <section className="glass mb-8 overflow-hidden rounded-2xl p-6 md:p-10 shadow-glow relative">
        <div className="absolute -top-24 -right-24 h-64 w-64 rounded-full bg-primary/30 blur-3xl pointer-events-none" />
        <div className="absolute -bottom-32 -left-16 h-72 w-72 rounded-full opacity-40 blur-3xl pointer-events-none" style={{ background: "var(--gradient-primary)" }} />
        <div className="relative inline-flex items-center gap-1.5 rounded-full border border-border/60 bg-background/40 px-2.5 py-1 text-xs font-medium text-muted-foreground backdrop-blur">
          <Sparkles className="h-3 w-3 text-primary" /> Powered by AI
        </div>
        <h1 className="relative mt-4 text-3xl font-semibold tracking-tight md:text-5xl">
          Your <span className="gradient-text">AI workplace</span> productivity suite
        </h1>
        <p className="relative mt-3 max-w-2xl text-sm text-muted-foreground md:text-base">
          Draft emails, summarize meetings, plan tasks, research topics, and chat with an AI assistant — all in one clean workspace.
        </p>
      </section>

      <h2 className="mb-3 text-sm font-medium text-muted-foreground uppercase tracking-wider">Tools</h2>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {tools.map((t) => (
          <Link
            key={t.url}
            to={t.url}
            className="group glass rounded-xl p-5 transition-all duration-300 hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-glow"
          >
            <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-lg gradient-primary text-primary-foreground shadow-glow transition-transform group-hover:scale-110">
              <t.icon className="h-4 w-4" />
            </div>
            <h3 className="text-base font-semibold tracking-tight group-hover:gradient-text">{t.title}</h3>
            <p className="mt-1 text-sm text-muted-foreground">{t.desc}</p>
          </Link>
        ))}
      </div>

      <div className="mt-10 flex items-start gap-3 glass rounded-lg p-4 text-sm text-muted-foreground">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
        <p>
          <span className="font-medium text-foreground">Responsible AI:</span> Outputs are generated by AI and may contain
          mistakes, biases, or outdated information. Always review and verify before sending, sharing, or acting on results.
        </p>
      </div>
    </div>
  );
}
