import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";
import { Mail, FileText, ListTodo, Search, MessageSquare, AlertTriangle, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Dashboard — WorkAI" },
      { name: "description", content: "Your AI-powered workplace productivity dashboard." },
    ],
  }),
  component: Index,
});

const tools = [
  { title: "Smart Email Generator", desc: "Draft professional emails from a short brief.", url: "/email", icon: Mail },
  { title: "Meeting Notes Summarizer", desc: "Turn raw notes into clean summaries & action items.", url: "/meetings", icon: FileText },
  { title: "AI Task Planner", desc: "Break goals into an organized, prioritized plan.", url: "/planner", icon: ListTodo },
  { title: "AI Research Assistant", desc: "Get structured briefs on any topic, fast.", url: "/research", icon: Search },
  { title: "AI Chatbot", desc: "Conversational assistant for any workplace task.", url: "/chat", icon: MessageSquare },
];

function Index() {
  return (
    <div className="mx-auto w-full max-w-6xl px-4 py-8 md:px-8 md:py-12">
      <section className="mb-8 rounded-2xl border bg-gradient-to-br from-accent/40 via-background to-background p-6 md:p-10">
        <div className="inline-flex items-center gap-1.5 rounded-full border bg-background/60 px-2.5 py-1 text-xs font-medium text-muted-foreground">
          <Sparkles className="h-3 w-3 text-primary" /> Powered by Lovable AI
        </div>
        <h1 className="mt-4 text-3xl font-semibold tracking-tight md:text-4xl">
          Your AI workplace productivity suite
        </h1>
        <p className="mt-2 max-w-2xl text-sm text-muted-foreground md:text-base">
          Draft emails, summarize meetings, plan tasks, research topics, and chat with an AI assistant — all in one clean workspace.
        </p>
      </section>

      <h2 className="mb-3 text-sm font-medium text-muted-foreground">Tools</h2>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {tools.map((t) => (
          <Link
            key={t.url}
            to={t.url}
            className="group rounded-xl border bg-card p-5 transition-all hover:border-primary/40 hover:shadow-sm"
          >
            <div className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-accent text-accent-foreground group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
              <t.icon className="h-4 w-4" />
            </div>
            <h3 className="text-base font-semibold tracking-tight">{t.title}</h3>
            <p className="mt-1 text-sm text-muted-foreground">{t.desc}</p>
          </Link>
        ))}
      </div>

      <div className="mt-10 flex items-start gap-3 rounded-lg border bg-muted/40 p-4 text-sm text-muted-foreground">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
        <p>
          <span className="font-medium text-foreground">Responsible AI:</span> Outputs are generated by AI and may contain
          mistakes, biases, or outdated information. Always review and verify before sending, sharing, or acting on results.
        </p>
      </div>
    </div>
  );
}
